### ISSUE TITLE
Update arrow order when end is modified to maintain high-low order

### ISSUE THREAD

**Issue by Tirpitz93** [DreierF/MyTargets#113]

**Comment by DreierF** [comment]
This is indeed an issue that should be addressed.
Note to myself:
I would suggest to throw away the premise that the shot id determines the order shots are shown (Current implementation). Because this would mean we would have to (conceptually) change the primary key of the shot. Instead the passe should get sorted before it is shown. This also makes it possible to show spot results in correct order while keeping the information which spot face the shot belongs to. Hope this was not too cryptic ^^

**Comment by Tirpitz93** [comment]
Thats what I was thinking, just sort by score when retrieving the values, that should be a one line edit.

**Comment by DreierF** [comment]
Your right. We just need to make sure that the shots are drawn on the correct spot faces.
