### ISSUE TITLE
Android Wear App not saving ends

### ISSUE THREAD

**Issue by carldini** [DreierF/MyTargets#340]
I'd love to use the wear interface but it's not saving the ends to the phone.
After getting the "Saved" dialog appear, nothing has updated on my phone.. it's still at End 1.

I'm guessing that I'm doing something daft?

Phone App Version is 2.5.0 (77) on a Pixel 2
Wear App is on a Huawei Watch 2 Classic

Thanks,
Carl

**Comment by DreierF** [comment]
Hi Carl,

Please try 3.0.0-beta 4 to see if the issue is already fixed. I had a bunch of Android Wear related fixes in there.
To do so join our group and follow the instructions in the pinned post. Thanks
https://plus.google.com/communities/102686119334423317437

**Comment by carldini** [comment]
Yup, loads better! Threw some ends through the watch and saw them appear in
the phone. Thanks for preemptively fixing it :)

If the phone is locked when you submit ends, it seems to be behind when you
unlock it. Reporting end 3/20 when the watch is on end 5.

It does catch up when you push the next end though.
I'll play with this some more tonight.

Carl.

**Comment by DreierF** [comment]
That's right, but it's very hard to fix that, because the input screen stops listening for updates from the watch when its getting destroyed by the system, which happens after the phone is locked for some time. When you unlock it, it just remembers the last end that you had open. Though I'll try to fix this
