### ISSUE TITLE
Share Function Bug

### ISSUE THREAD

**Issue by zar237** [DreierF/MyTargets#81]
I use this app to share scores each week for our outdoor League and I have noticed that when the picture is added into the text message as a multimedia text, only about half of the image is visible. I am using a Galaxy S7 and the message+ app from Verizon. Thanks!

**Comment by DreierF** [comment]
The issue is that the webview which provides the content of the image tells the app that it has finished loading the scoresheet, but the bas64 image gets drawn for the first time afterwards. So when timing is bad the image is taken while the image is still drawing. I will fix this by separating the dispersion pattern view from the scoresheet entirely.
